require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmergenciesController do

  # This should return the minimal set of attributes required to create a valid
  # Emergency. As you add validations to Emergency, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "details" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmergenciesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all emergencies as @emergencies" do
      emergency = Emergency.create! valid_attributes
      get :index, {}, valid_session
      assigns(:emergencies).should eq([emergency])
    end
  end

  describe "GET show" do
    it "assigns the requested emergency as @emergency" do
      emergency = Emergency.create! valid_attributes
      get :show, {:id => emergency.to_param}, valid_session
      assigns(:emergency).should eq(emergency)
    end
  end

  describe "GET new" do
    it "assigns a new emergency as @emergency" do
      get :new, {}, valid_session
      assigns(:emergency).should be_a_new(Emergency)
    end
  end

  describe "GET edit" do
    it "assigns the requested emergency as @emergency" do
      emergency = Emergency.create! valid_attributes
      get :edit, {:id => emergency.to_param}, valid_session
      assigns(:emergency).should eq(emergency)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Emergency" do
        expect {
          post :create, {:emergency => valid_attributes}, valid_session
        }.to change(Emergency, :count).by(1)
      end

      it "assigns a newly created emergency as @emergency" do
        post :create, {:emergency => valid_attributes}, valid_session
        assigns(:emergency).should be_a(Emergency)
        assigns(:emergency).should be_persisted
      end

      it "redirects to the created emergency" do
        post :create, {:emergency => valid_attributes}, valid_session
        response.should redirect_to(Emergency.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved emergency as @emergency" do
        # Trigger the behavior that occurs when invalid params are submitted
        Emergency.any_instance.stub(:save).and_return(false)
        post :create, {:emergency => { "details" => "invalid value" }}, valid_session
        assigns(:emergency).should be_a_new(Emergency)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Emergency.any_instance.stub(:save).and_return(false)
        post :create, {:emergency => { "details" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested emergency" do
        emergency = Emergency.create! valid_attributes
        # Assuming there are no other emergencies in the database, this
        # specifies that the Emergency created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Emergency.any_instance.should_receive(:update).with({ "details" => "MyString" })
        put :update, {:id => emergency.to_param, :emergency => { "details" => "MyString" }}, valid_session
      end

      it "assigns the requested emergency as @emergency" do
        emergency = Emergency.create! valid_attributes
        put :update, {:id => emergency.to_param, :emergency => valid_attributes}, valid_session
        assigns(:emergency).should eq(emergency)
      end

      it "redirects to the emergency" do
        emergency = Emergency.create! valid_attributes
        put :update, {:id => emergency.to_param, :emergency => valid_attributes}, valid_session
        response.should redirect_to(emergency)
      end
    end

    describe "with invalid params" do
      it "assigns the emergency as @emergency" do
        emergency = Emergency.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Emergency.any_instance.stub(:save).and_return(false)
        put :update, {:id => emergency.to_param, :emergency => { "details" => "invalid value" }}, valid_session
        assigns(:emergency).should eq(emergency)
      end

      it "re-renders the 'edit' template" do
        emergency = Emergency.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Emergency.any_instance.stub(:save).and_return(false)
        put :update, {:id => emergency.to_param, :emergency => { "details" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested emergency" do
      emergency = Emergency.create! valid_attributes
      expect {
        delete :destroy, {:id => emergency.to_param}, valid_session
      }.to change(Emergency, :count).by(-1)
    end

    it "redirects to the emergencies list" do
      emergency = Emergency.create! valid_attributes
      delete :destroy, {:id => emergency.to_param}, valid_session
      response.should redirect_to(emergencies_url)
    end
  end

end
